server {
    listen 80;
    server_name yangbansanghoe.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name yangbansanghoe.com;

    ssl_certificate /etc/letsencrypt/live/yangbansanghoe.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yangbansanghoe.com/privkey.pem;

    location /api/ {
        proxy_pass http://backend:8080;
    }

    location / {
        proxy_pass http://frontend:80;
    }
}